### ISSUE TITLE
Problems being solved backwards order

### ISSUE THREAD

**Issue by tslater2006** [eduherminio/AoCHelper#137]
I added a Day02.cs today, and tried SolveLast() but it ran Day01 again. Running Solver.SolveAll() results in this output:

![image](https://user-images.githubusercontent.com/1731714/205319318-9871a50b-8fe5-4138-8386-ff8efa076355.png)

As far as I can tell the SolveAll() relies on  LoadAllProblems() which just scans the assembly for classes that extend BaseDay but doesn't sort them? Unsure how to resolve this on my side, hoping you have some ideas (or I'm doing something wrong).

Project layout:
![image](https://user-images.githubusercontent.com/1731714/205319595-2fcac499-fca4-41d5-93a5-3fe407f4d19f.png)

**Comment by tslater2006** [comment]
I've also tried the naming convention Day_xx with an underscore between the class prefix and index number.

**Comment by eduherminio** [comment]
It's happening because the lack of namespace in `Day02.cs` file.
I'll have a look to see if I can fix the default behavior when something like this happens, but adding a namespace there should solve the issue for now.

**Comment by tslater2006** [comment]
Perfect! thanks for such a quick response. Will close this issue.
