### ISSUE TITLE
Solve problems from referenced assemblies

### ISSUE THREAD

**Issue by codemonkey85** [eduherminio/AoCHelper#180]
I was wondering if it might be possible to have either additional assemblies, or at least one alternative assembly for `Solver` to solve problems from. I have [a project structure for showing solutions in both a console app and a web app](https://github.com/codemonkey85/Advent-of-Code-2023), and I'd like to be able to reference a library containing the problems / solutions.

**Comment by codemonkey85** [comment]
I created #181 to try and solve this myself.

**Comment by eduherminio** [comment]
Hey @codemonkey85, first of all thanks for considering using AoCHelper and raising this issue and the associated PR.

Just to make sure thatwe're in the same page, before discussing the potential solution: if I understand your use case correctly, you don't really have the need to load the problems from multiple assemblies for the same Solver, bur rather to load them from a different assembly other than the entry one, right?

**Comment by eduherminio** [comment]
I'm also thinking right now how the potential solution that is chosen for this issue can influence/facilitate #92 in the future.

**Comment by eduherminio** [comment]
Close by #181.
