### ISSUE TITLE
Clear Console happens regardless of flag

### ISSUE THREAD

**Issue by tslater2006** [eduherminio/AoCHelper#26]
Regardless if I pass true or false for ClearConsole, it clears anyways. Looking at the code here, it seems it will do a clear no matter what, just either a Console.Clear or an AnsiConsole Clear.

I'd like to be able to use Console.WriteLine (or AnsiConsole.WriteLine) for debugging and not have those lines wiped out by the results.

![image](https://user-images.githubusercontent.com/1731714/100634330-c8f76e80-32f4-11eb-840f-f917754d0d16.png)

**Comment by eduherminio** [comment]
Hi @tslater2006,

If you use `Solver.SolveLast(false)` or `Solver.Solve<T>(false)`, you should be able to **scroll up** in your terminal and see the previous results and your (`Console.WriteLine`) logs?
Can you confirm me that, when scrolling up, you cannot see the previous runs?

**Comment by tslater2006** [comment]
Doh! didn't realize you could scroll up :).. thanks!

![image](https://user-images.githubusercontent.com/1731714/100647533-4a56fd00-3305-11eb-9890-2d1c50bcc048.png)

**Comment by eduherminio** [comment]
Thanks to you 😃
