### ISSUE TITLE
Solver without static context?

### ISSUE THREAD

**Issue by jetersen** [eduherminio/AoCHelper#34]
Would be nice if I could dependency inject the solver.

What you've done in your pull.ps1 I have done in C# by injecting a http client.

**Comment by eduherminio** [comment]
Could you provide some more context about the scenario where you want the `Solver` to be injected via DI?
It used to be non-static, but from [v0.8.0](https://github.com/eduherminio/AoCHelper/releases/tag/v0.8.0) I decided to go down the static path and make the base problem class more extensible instead.

**Comment by jetersen** [comment]
I want the solver to actually have access to the base problem with a fetch input method for that I need a http client which I started using dependency injection for the use case.

The fetch input will attempt to check if the `InputFilePath` exists if not go fetch the input file.

**Comment by eduherminio** [comment]
Something you can do is creating your own `CustomBaseProblem` class, inheriting either `BaseProblem` or `BaseDay`, and either doing that conditional fetching in the constructor or in an overridden `FileInput` getter property.
I'm aware that such a solution doesn't allow DI though, but I'm afraid I don't have plans to make the `Solver` non-static for the time being unless there's more demand for it.

**Comment by jetersen** [comment]
I ended up implementing the solver for my needs.

Solver is mixing the table drawing and solving parts.

So I changed the solver to accept tasks and create a separate method for drawing since working with asynchronous tasks does not work well when drawing 🙈

So the solve methods does not work with the table and clearing of terminal at all.
Makes the code easier to read using expression bodies.

The solver now also works with dependency injection to load all the problems.

**Comment by eduherminio** [comment]
That's terrific @jetersen, looking forward to seeing the result of it if you ever decide to open source it.

**Comment by jetersen** [comment]
@eduherminio here you go https://github.com/jetersen/adventofcode

**Comment by eduherminio** [comment]
Looks great @jetersen, I'll let you know if at some point I go back to the non-static `Solver` idea, in case we can rejoin our paths.

**Comment by eduherminio** [comment]
@jetersen Can I ask kindly you to add the MIT license to your repo?
You can (and should!) add your name under mine there, but keeping a copy of the original license and attribution is [a requirement](https://softwareengineering.stackexchange.com/questions/386582/altering-author-names-in-mit-license) (almost the only one) for any derivate work.

**Comment by jetersen** [comment]
I was going to. No worries 🙈

**Comment by jetersen** [comment]
Do you want the license in the files? or just in the outer LICENSE file?

**Comment by eduherminio** [comment]
The outer license file is fine for me, thanks!

**Comment by jetersen** [comment]
Done and Done:
https://github.com/jetersen/adventofcode/commit/b247df85f818401f64524ed8a8ef268069b51759
https://github.com/jetersen/adventofcode/commit/a8c258fcc896a44bb2f73ebc98081db5765a9671
